/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author rramirez
 */
public class FrmLobbyJuego extends javax.swing.JFrame {

    /**
     * Creates new form FrmLobbyJuego
     */
    public FrmLobbyJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneTamTab = new javax.swing.JPanel();
        LblTab = new javax.swing.JLabel();
        BtnListo4 = new javax.swing.JButton();
        BtnImgPlayer4 = new javax.swing.JButton();
        LblNombre4 = new javax.swing.JLabel();
        LblColorP4 = new javax.swing.JLabel();
        BtnListo2 = new javax.swing.JButton();
        BtnImgPlayer2 = new javax.swing.JButton();
        LblColorP2 = new javax.swing.JLabel();
        LblNombre2 = new javax.swing.JLabel();
        BtnListo3 = new javax.swing.JButton();
        BtnImgPlayer3 = new javax.swing.JButton();
        LblNombre3 = new javax.swing.JLabel();
        LblColorP3 = new javax.swing.JLabel();
        LblColorP = new javax.swing.JLabel();
        BtnDer1 = new javax.swing.JButton();
        BtnIzq1 = new javax.swing.JButton();
        LblNombre = new javax.swing.JLabel();
        BtnImgPlayer = new javax.swing.JButton();
        BtnListo = new javax.swing.JButton();
        LblContinuar = new javax.swing.JLabel();
        BtnContinuar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        LblTablero = new javax.swing.JLabel();
        BtnTam2 = new javax.swing.JButton();
        BtnTam1 = new javax.swing.JButton();
        LblFondo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPaneTamTab.setBackground(new java.awt.Color(153, 153, 153));
        JPaneTamTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTab.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        LblTab.setForeground(new java.awt.Color(255, 255, 255));
        LblTab.setText("Tablero");
        JPaneTamTab.add(LblTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, -1, -1));

        BtnListo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Palomita.png"))); // NOI18N
        BtnListo4.setContentAreaFilled(false);
        JPaneTamTab.add(BtnListo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 520, 110, 80));

        BtnImgPlayer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P11m.png"))); // NOI18N
        BtnImgPlayer4.setContentAreaFilled(false);
        JPaneTamTab.add(BtnImgPlayer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 600, 250, -1));

        LblNombre4.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        LblNombre4.setForeground(new java.awt.Color(255, 255, 255));
        LblNombre4.setText("(Nombre)");
        JPaneTamTab.add(LblNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 850, -1, 60));

        LblColorP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ColorRosaPlayer.png"))); // NOI18N
        JPaneTamTab.add(LblColorP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 910, 200, 80));

        BtnListo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Palomita.png"))); // NOI18N
        BtnListo2.setContentAreaFilled(false);
        JPaneTamTab.add(BtnListo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 40, 110, 80));

        BtnImgPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P8m.png"))); // NOI18N
        BtnImgPlayer2.setContentAreaFilled(false);
        JPaneTamTab.add(BtnImgPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 120, 250, -1));

        LblColorP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ColorAzulPlayer.png"))); // NOI18N
        JPaneTamTab.add(LblColorP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 430, 200, 80));

        LblNombre2.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        LblNombre2.setForeground(new java.awt.Color(255, 255, 255));
        LblNombre2.setText("(Nombre)");
        JPaneTamTab.add(LblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 370, -1, 60));

        BtnListo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Palomita.png"))); // NOI18N
        BtnListo3.setContentAreaFilled(false);
        JPaneTamTab.add(BtnListo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 110, 70));

        BtnImgPlayer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P4m.png"))); // NOI18N
        BtnImgPlayer3.setContentAreaFilled(false);
        JPaneTamTab.add(BtnImgPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 250, -1));

        LblNombre3.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        LblNombre3.setForeground(new java.awt.Color(255, 255, 255));
        LblNombre3.setText("(Nombre)");
        JPaneTamTab.add(LblNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 840, -1, 60));

        LblColorP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ColorVerdePlayer.png"))); // NOI18N
        JPaneTamTab.add(LblColorP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 900, 190, 80));

        LblColorP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ColorRojoPlayer.png"))); // NOI18N
        JPaneTamTab.add(LblColorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 200, 80));

        BtnDer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FlechaDer.png"))); // NOI18N
        BtnDer1.setContentAreaFilled(false);
        JPaneTamTab.add(BtnDer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 110, 60));

        BtnIzq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FlechaIZQ.png"))); // NOI18N
        BtnIzq1.setContentAreaFilled(false);
        JPaneTamTab.add(BtnIzq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 110, 60));

        LblNombre.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(255, 255, 255));
        LblNombre.setText("(Nombre)");
        JPaneTamTab.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 60));

        BtnImgPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P1m.png"))); // NOI18N
        BtnImgPlayer.setContentAreaFilled(false);
        JPaneTamTab.add(BtnImgPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, -1));

        BtnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Palomita.png"))); // NOI18N
        BtnListo.setContentAreaFilled(false);
        JPaneTamTab.add(BtnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 110, 80));

        LblContinuar.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        LblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        LblContinuar.setText("Continuar");
        JPaneTamTab.add(LblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 890, -1, -1));

        BtnContinuar.setBackground(new java.awt.Color(153, 0, 0));
        BtnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4.png"))); // NOI18N
        BtnContinuar.setBorder(null);
        BtnContinuar.setContentAreaFilled(false);
        BtnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContinuarActionPerformed(evt);
            }
        });
        JPaneTamTab.add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 880, -1, -1));

        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditarImg.png"))); // NOI18N
        BtnEditar.setContentAreaFilled(false);
        JPaneTamTab.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 110));

        LblTablero.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        LblTablero.setForeground(new java.awt.Color(255, 255, 255));
        LblTablero.setText("30 x 30");
        JPaneTamTab.add(LblTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 520, -1, -1));

        BtnTam2.setBackground(new java.awt.Color(153, 0, 0));
        BtnTam2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RICHE.png"))); // NOI18N
        BtnTam2.setBorder(null);
        BtnTam2.setContentAreaFilled(false);
        BtnTam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTam2ActionPerformed(evt);
            }
        });
        JPaneTamTab.add(BtnTam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 270, -1));

        BtnTam1.setBackground(new java.awt.Color(153, 0, 0));
        BtnTam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TIMBI.png"))); // NOI18N
        BtnTam1.setBorder(null);
        BtnTam1.setContentAreaFilled(false);
        BtnTam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTam1ActionPerformed(evt);
            }
        });
        JPaneTamTab.add(BtnTam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 270, -1));

        LblFondo.setForeground(new java.awt.Color(255, 255, 255));
        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoReg1.1.png"))); // NOI18N
        LblFondo.setPreferredSize(new java.awt.Dimension(1920, 1080));
        JPaneTamTab.add(LblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jTextField1.setText("jTextField1");
        JPaneTamTab.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneTamTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneTamTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnContinuarActionPerformed

    private void BtnTam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTam2ActionPerformed

    private void BtnTam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTam1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmLobbyJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmLobbyJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmLobbyJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmLobbyJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLobbyJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JButton BtnDer1;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnImgPlayer;
    private javax.swing.JButton BtnImgPlayer2;
    private javax.swing.JButton BtnImgPlayer3;
    private javax.swing.JButton BtnImgPlayer4;
    private javax.swing.JButton BtnIzq1;
    private javax.swing.JButton BtnListo;
    private javax.swing.JButton BtnListo2;
    private javax.swing.JButton BtnListo3;
    private javax.swing.JButton BtnListo4;
    private javax.swing.JButton BtnTam1;
    private javax.swing.JButton BtnTam2;
    private javax.swing.JPanel JPaneTamTab;
    private javax.swing.JLabel LblColorP;
    private javax.swing.JLabel LblColorP2;
    private javax.swing.JLabel LblColorP3;
    private javax.swing.JLabel LblColorP4;
    private javax.swing.JLabel LblContinuar;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblNombre2;
    private javax.swing.JLabel LblNombre3;
    private javax.swing.JLabel LblNombre4;
    private javax.swing.JLabel LblTab;
    private javax.swing.JLabel LblTablero;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
