/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Jugador;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class FrmRegistro extends javax.swing.JFrame {

    private final ArrayList<Color> coloresDisponibles = new ArrayList<>();
    private static int colorIndex = 0;
    private ImageIcon avatarSeleccionado;
    private JPanel panelAvatares;

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        initComponents();
        cargarAvatares();
        inicializarColores();
    }

    private void cargarAvatares() {
        String[] nombresAvatares = {
            "GATO.png", "LEIA.png", "LOBO.png", "PINGUINO.png",
            "RANA.png", "ROBOCOB.png", "SOLDADO.png"
        };

         panelAvatares = new JPanel(new GridLayout(2, 4, 15, 15)); 
        panelAvatares.setOpaque(false);
        JPaneRegistro.add(panelAvatares, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 480, 300));

        for (String nombre : nombresAvatares) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Avatares/" + nombre));
            JButton btnAvatar = new JButton(icon);
            btnAvatar.setBorder(BorderFactory.createEmptyBorder());
            btnAvatar.setBackground(Color.WHITE);

            btnAvatar.addActionListener(e -> {
                if (avatarSeleccionado != icon) {
                    avatarSeleccionado = icon;
                    JOptionPane.showMessageDialog(this, "Avatar seleccionado: " + nombre);
                }
            });

            panelAvatares.add(btnAvatar);
        }

       JPaneRegistro.repaint();
        JPaneRegistro.revalidate();
    }

    private void inicializarColores() {
        coloresDisponibles.add(Color.BLUE);
        coloresDisponibles.add(Color.RED);
        coloresDisponibles.add(Color.GREEN.darker());
        coloresDisponibles.add(Color.ORANGE.darker());
    }

    private void registrarJugador() {
        String nombre = TxtUsuario.getText().trim();

        if (nombre.isEmpty() || nombre.equals("Usuario")) {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre válido.");
            return;
        }

        if (avatarSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un avatar.");
            return;
        }

        Color colorAsignado = coloresDisponibles.get(colorIndex % coloresDisponibles.size());
        colorIndex++;

        Jugador jugador = new Jugador(nombre, colorAsignado, avatarSeleccionado);

        FrmJuego frmJuego = new FrmJuego(jugador);
        frmJuego.setVisible(true);
        this.dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneRegistro = new javax.swing.JPanel();
        LblRegistro = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        BtnRegistrarse = new javax.swing.JButton();
        LblFondoReg = new javax.swing.JLabel();
        LblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPaneRegistro.setBackground(new java.awt.Color(153, 153, 153));
        JPaneRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblRegistro.setBackground(new java.awt.Color(255, 255, 255));
        LblRegistro.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        LblRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LblRegistro.setText("Registro");
        JPaneRegistro.add(LblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 240, 100));

        TxtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TxtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        TxtUsuario.setText("Usuario");
        TxtUsuario.setToolTipText("Usuario");
        TxtUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TxtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtUsuarioFocusLost(evt);
            }
        });
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        JPaneRegistro.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 480, 70));

        BtnRegistrarse.setBackground(new java.awt.Color(128, 30, 47));
        BtnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BtnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrarse.setText("Registrarse");
        BtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarseActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 800, 250, 80));

        LblFondoReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 5.png"))); // NOI18N
        LblFondoReg.setAlignmentY(0.0F);
        LblFondoReg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LblFondoReg.setPreferredSize(new java.awt.Dimension(623, 1000));
        JPaneRegistro.add(LblFondoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 630, 910));

        LblFondo.setForeground(new java.awt.Color(255, 255, 255));
        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoReg1.1.png"))); // NOI18N
        LblFondo.setPreferredSize(new java.awt.Dimension(1920, 1080));
        JPaneRegistro.add(LblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -20, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUsuarioFocusGained
        if (TxtUsuario.getText().equals("Usuario")) {
            TxtUsuario.setText("");
            TxtUsuario.setForeground(new Color(0, 0, 0));
        }

    }//GEN-LAST:event_TxtUsuarioFocusGained

    private void TxtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtUsuarioFocusLost
        if (TxtUsuario.getText().isEmpty()) {
            TxtUsuario.setText("Usuario");
            TxtUsuario.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_TxtUsuarioFocusLost

    private void BtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarseActionPerformed
        registrarJugador();
    }//GEN-LAST:event_BtnRegistrarseActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarse;
    private javax.swing.JPanel JPaneRegistro;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JLabel LblFondoReg;
    private javax.swing.JLabel LblRegistro;
    private javax.swing.JTextField TxtUsuario;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new FrmRegistro().setVisible(true);
        });
    }

}
