/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author rramirez
 */
public class FrmEditarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditarPerfil
     */
    public FrmEditarPerfil() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnP1 = new javax.swing.JButton();
        BtnP2 = new javax.swing.JButton();
        BtnP3 = new javax.swing.JButton();
        BtnP4 = new javax.swing.JButton();
        BtnP5 = new javax.swing.JButton();
        BtnP6 = new javax.swing.JButton();
        BtnP7 = new javax.swing.JButton();
        BtnP8 = new javax.swing.JButton();
        BtnP9 = new javax.swing.JButton();
        BtnP10 = new javax.swing.JButton();
        BtnP11 = new javax.swing.JButton();
        BtnP12 = new javax.swing.JButton();
        BtnP13 = new javax.swing.JButton();
        BtnP14 = new javax.swing.JButton();
        BtnP15 = new javax.swing.JButton();
        BtnP16 = new javax.swing.JButton();
        LblCancelar = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        LblAceptar = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        LblNombrePerfilBajo = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        LblNombrePerfil = new javax.swing.JLabel();
        Lbln = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        LblRegistro = new javax.swing.JLabel();
        LblFondo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPaneRegistro.setBackground(new java.awt.Color(153, 153, 153));
        JPaneRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P1m.png"))); // NOI18N
        JPaneRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 210, -1, -1));

        BtnP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P1.png"))); // NOI18N
        BtnP1.setContentAreaFilled(false);
        BtnP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP1ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 100, -1));

        BtnP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P2.png"))); // NOI18N
        BtnP2.setContentAreaFilled(false);
        BtnP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP2ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 100, -1));

        BtnP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P3.png"))); // NOI18N
        BtnP3.setContentAreaFilled(false);
        BtnP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP3ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 100, -1));

        BtnP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P4.png"))); // NOI18N
        BtnP4.setContentAreaFilled(false);
        BtnP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP4ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 470, 100, -1));

        BtnP5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P5.png"))); // NOI18N
        BtnP5.setContentAreaFilled(false);
        BtnP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP5ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 100, -1));

        BtnP6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P6.png"))); // NOI18N
        BtnP6.setContentAreaFilled(false);
        BtnP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP6ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 100, -1));

        BtnP7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P7.png"))); // NOI18N
        BtnP7.setContentAreaFilled(false);
        BtnP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP7ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, 100, -1));

        BtnP8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P8.png"))); // NOI18N
        BtnP8.setContentAreaFilled(false);
        BtnP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP8ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 570, 100, -1));

        BtnP9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P9.png"))); // NOI18N
        BtnP9.setContentAreaFilled(false);
        BtnP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP9ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, 100, -1));

        BtnP10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P10.png"))); // NOI18N
        BtnP10.setContentAreaFilled(false);
        BtnP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP10ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 100, -1));

        BtnP11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P11.png"))); // NOI18N
        BtnP11.setContentAreaFilled(false);
        BtnP11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP11ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 670, 100, -1));

        BtnP12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P12.png"))); // NOI18N
        BtnP12.setContentAreaFilled(false);
        BtnP12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP12ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 670, 100, -1));

        BtnP13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P13.png"))); // NOI18N
        BtnP13.setContentAreaFilled(false);
        BtnP13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP13ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 770, 100, -1));

        BtnP14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P14.png"))); // NOI18N
        BtnP14.setContentAreaFilled(false);
        BtnP14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP14ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 770, 100, -1));

        BtnP15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P15.png"))); // NOI18N
        BtnP15.setContentAreaFilled(false);
        BtnP15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP15ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP15, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 770, 100, -1));

        BtnP16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P16.png"))); // NOI18N
        BtnP16.setContentAreaFilled(false);
        BtnP16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnP16ActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnP16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 770, 100, -1));

        LblCancelar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblCancelar.setText("Cancelar");
        LblCancelar.setToolTipText("");
        JPaneRegistro.add(LblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 890, 120, 50));

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4.png"))); // NOI18N
        BtnCancelar.setContentAreaFilled(false);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 880, -1, -1));

        LblAceptar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblAceptar.setText("Aceptar");
        LblAceptar.setToolTipText("");
        JPaneRegistro.add(LblAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 890, 120, 50));

        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4.png"))); // NOI18N
        BtnAceptar.setContentAreaFilled(false);
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        JPaneRegistro.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 880, -1, 80));

        LblNombrePerfilBajo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblNombrePerfilBajo.setForeground(new java.awt.Color(255, 255, 255));
        LblNombrePerfilBajo.setText("(Nombre)");
        JPaneRegistro.add(LblNombrePerfilBajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 450, 240, 60));

        Nombre1.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setText("Avatar");
        JPaneRegistro.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 120, -1));

        LblNombrePerfil.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LblNombrePerfil.setForeground(new java.awt.Color(0, 0, 0));
        LblNombrePerfil.setText("(Nombre)");
        JPaneRegistro.add(LblNombrePerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 250, 60));

        Lbln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4 white.png"))); // NOI18N
        JPaneRegistro.add(Lbln, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, 80));

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Nombre.setForeground(new java.awt.Color(204, 204, 204));
        Nombre.setText("Nombre");
        JPaneRegistro.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, -1, -1));

        LblRegistro.setBackground(new java.awt.Color(255, 255, 255));
        LblRegistro.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        LblRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LblRegistro.setText("Editar Perfil");
        JPaneRegistro.add(LblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 340, 100));

        LblFondo.setForeground(new java.awt.Color(255, 255, 255));
        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoReg1.1.png"))); // NOI18N
        LblFondo.setPreferredSize(new java.awt.Dimension(1920, 1080));
        JPaneRegistro.add(LblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jTextField1.setText("jTextField1");
        JPaneRegistro.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP1ActionPerformed

    private void BtnP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP2ActionPerformed

    private void BtnP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP3ActionPerformed

    private void BtnP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP4ActionPerformed

    private void BtnP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP5ActionPerformed

    private void BtnP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP6ActionPerformed

    private void BtnP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP7ActionPerformed

    private void BtnP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP8ActionPerformed

    private void BtnP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP9ActionPerformed

    private void BtnP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP10ActionPerformed

    private void BtnP11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP11ActionPerformed

    private void BtnP12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP12ActionPerformed

    private void BtnP13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP13ActionPerformed

    private void BtnP14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP14ActionPerformed

    private void BtnP15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP15ActionPerformed

    private void BtnP16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnP16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnP16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmEditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnP1;
    private javax.swing.JButton BtnP10;
    private javax.swing.JButton BtnP11;
    private javax.swing.JButton BtnP12;
    private javax.swing.JButton BtnP13;
    private javax.swing.JButton BtnP14;
    private javax.swing.JButton BtnP15;
    private javax.swing.JButton BtnP16;
    private javax.swing.JButton BtnP2;
    private javax.swing.JButton BtnP3;
    private javax.swing.JButton BtnP4;
    private javax.swing.JButton BtnP5;
    private javax.swing.JButton BtnP6;
    private javax.swing.JButton BtnP7;
    private javax.swing.JButton BtnP8;
    private javax.swing.JButton BtnP9;
    private javax.swing.JPanel JPaneRegistro;
    private javax.swing.JLabel LblAceptar;
    private javax.swing.JLabel LblCancelar;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JLabel LblNombrePerfil;
    private javax.swing.JLabel LblNombrePerfilBajo;
    private javax.swing.JLabel LblRegistro;
    private javax.swing.JLabel Lbln;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
