/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author rramirez
 */
public class FrmTamanoTablero extends javax.swing.JFrame {

    /**
     * Creates new form FrmTamanoTablero
     */
    public FrmTamanoTablero() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneTamTab = new javax.swing.JPanel();
        LblSelec = new javax.swing.JLabel();
        LblContinuar = new javax.swing.JLabel();
        BtnContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnServidor = new javax.swing.JButton();
        Lbl30x30 = new javax.swing.JLabel();
        BtnTam3 = new javax.swing.JButton();
        Lbl20x = new javax.swing.JLabel();
        BtnTam2 = new javax.swing.JButton();
        Lbl10x = new javax.swing.JLabel();
        BtnTam1 = new javax.swing.JButton();
        LblRegistro = new javax.swing.JLabel();
        LblFondo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPaneTamTab.setBackground(new java.awt.Color(153, 153, 153));
        JPaneTamTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblSelec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblSelec.setForeground(new java.awt.Color(255, 255, 255));
        LblSelec.setText("Seleccione");
        JPaneTamTab.add(LblSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, -1, -1));

        LblContinuar.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        LblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        LblContinuar.setText("Continuar");
        JPaneTamTab.add(LblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 890, -1, -1));

        BtnContinuar.setBackground(new java.awt.Color(153, 0, 0));
        BtnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4.png"))); // NOI18N
        BtnContinuar.setBorder(null);
        BtnContinuar.setContentAreaFilled(false);
        BtnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContinuarActionPerformed(evt);
            }
        });
        JPaneTamTab.add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 880, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Servidor");
        JPaneTamTab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 740, -1, 50));

        BtnServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 3.png"))); // NOI18N
        BtnServidor.setContentAreaFilled(false);
        JPaneTamTab.add(BtnServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 730, 430, 80));

        Lbl30x30.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        Lbl30x30.setForeground(new java.awt.Color(255, 255, 255));
        Lbl30x30.setText("30 x 30");
        JPaneTamTab.add(Lbl30x30, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, -1, -1));

        BtnTam3.setBackground(new java.awt.Color(153, 0, 0));
        BtnTam3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4.png"))); // NOI18N
        BtnTam3.setBorder(null);
        BtnTam3.setContentAreaFilled(false);
        BtnTam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTam3ActionPerformed(evt);
            }
        });
        JPaneTamTab.add(BtnTam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, -1, -1));

        Lbl20x.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        Lbl20x.setForeground(new java.awt.Color(255, 255, 255));
        Lbl20x.setText("20 x 20");
        JPaneTamTab.add(Lbl20x, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        BtnTam2.setBackground(new java.awt.Color(153, 0, 0));
        BtnTam2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4.png"))); // NOI18N
        BtnTam2.setBorder(null);
        BtnTam2.setContentAreaFilled(false);
        BtnTam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTam2ActionPerformed(evt);
            }
        });
        JPaneTamTab.add(BtnTam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, -1, -1));

        Lbl10x.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        Lbl10x.setForeground(new java.awt.Color(255, 255, 255));
        Lbl10x.setText("10 x 10");
        JPaneTamTab.add(Lbl10x, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, -1, -1));

        BtnTam1.setBackground(new java.awt.Color(153, 0, 0));
        BtnTam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 4.png"))); // NOI18N
        BtnTam1.setBorder(null);
        BtnTam1.setContentAreaFilled(false);
        BtnTam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTam1ActionPerformed(evt);
            }
        });
        JPaneTamTab.add(BtnTam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, -1));

        LblRegistro.setBackground(new java.awt.Color(255, 255, 255));
        LblRegistro.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        LblRegistro.setForeground(new java.awt.Color(255, 255, 255));
        LblRegistro.setText("Seleccionar Tamaño Del Tablero");
        JPaneTamTab.add(LblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 910, 100));

        LblFondo.setForeground(new java.awt.Color(255, 255, 255));
        LblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoReg1.1.png"))); // NOI18N
        LblFondo.setPreferredSize(new java.awt.Dimension(1920, 1080));
        JPaneTamTab.add(LblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jTextField1.setText("jTextField1");
        JPaneTamTab.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneTamTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPaneTamTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTam1ActionPerformed

    private void BtnTam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTam2ActionPerformed

    private void BtnTam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTam3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTam3ActionPerformed

    private void BtnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmTamanoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmTamanoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmTamanoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmTamanoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTamanoTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JButton BtnServidor;
    private javax.swing.JButton BtnTam1;
    private javax.swing.JButton BtnTam2;
    private javax.swing.JButton BtnTam3;
    private javax.swing.JPanel JPaneTamTab;
    private javax.swing.JLabel Lbl10x;
    private javax.swing.JLabel Lbl20x;
    private javax.swing.JLabel Lbl30x30;
    private javax.swing.JLabel LblContinuar;
    private javax.swing.JLabel LblFondo;
    private javax.swing.JLabel LblRegistro;
    private javax.swing.JLabel LblSelec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
